using System.Collections.Generic;

namespace Swarm.Shared.EventBus.Events;

/// <summary>
/// Event published by the Editor to request the Agent system process a prompt.
/// </summary>
/// <param name="PromptId">A unique ID generated by the editor for this specific request.</param>
/// <param name="Prompt">The user's textual prompt.</param>
/// <param name="AdditionalContext">Optional dictionary for extra context (e.g., file paths, settings).</param>
public record SendPromptEvent(string PromptId, string Prompt, Dictionary<string, object>? AdditionalContext); 